/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.controladorapariencia;
import javax.swing.JOptionPane;
import modelo.apariencia;

/**
 *
 * @author crist
 */
public class apariencia1 extends javax.swing.JFrame {

   controladorapariencia autocontrolador = new controladorapariencia();
    
    
    /**
     * Creates new form apariencia1
     */
    public apariencia1() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bot_agregar = new javax.swing.JButton();
        txt_cedula_competidor = new javax.swing.JTextField();
        txt_cedula_representante = new javax.swing.JTextField();
        txt_color = new javax.swing.JTextField();
        txt_modificacion = new javax.swing.JTextField();
        txt_representante = new javax.swing.JTextField();
        bot_limpiar = new javax.swing.JButton();
        bot_siguiente = new javax.swing.JButton();
        lbl_error = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setVisible(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Ingresar Datos Apariencia");

        jLabel2.setText("Cedula Competidor:");

        jLabel3.setText("Cedula Representante:");

        jLabel4.setText("Color del auto:");

        jLabel5.setText("Modificaciones:");

        jLabel6.setText("Nombre representante:");

        bot_agregar.setText("Agregar");
        bot_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_agregarActionPerformed(evt);
            }
        });

        txt_cedula_competidor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cedula_competidorKeyTyped(evt);
            }
        });

        txt_cedula_representante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cedula_representanteKeyTyped(evt);
            }
        });

        txt_color.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_colorKeyTyped(evt);
            }
        });

        txt_modificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_modificacionKeyTyped(evt);
            }
        });

        txt_representante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_representanteKeyTyped(evt);
            }
        });

        bot_limpiar.setText("Limpiar");
        bot_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_limpiarActionPerformed(evt);
            }
        });

        bot_siguiente.setText("Siguiente>");
        bot_siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_siguienteActionPerformed(evt);
            }
        });

        lbl_error.setText(".");

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(bot_siguiente)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(bot_agregar)
                                .addGap(100, 100, 100)
                                .addComponent(bot_limpiar)))
                        .addGap(141, 141, 141))))
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(65, 65, 65)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_cedula_competidor)
                            .addComponent(txt_cedula_representante)
                            .addComponent(txt_color)
                            .addComponent(txt_modificacion)
                            .addComponent(txt_representante, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_cedula_competidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_cedula_representante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_modificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_representante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(lbl_error)
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bot_limpiar)
                    .addComponent(bot_agregar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(bot_siguiente)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bot_siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_siguienteActionPerformed
        apariencia2 apa = new apariencia2();
        apa.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bot_siguienteActionPerformed

    private void bot_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_limpiarActionPerformed
        // TODO add your handling code here:
        txt_cedula_competidor.setText(" ");
        txt_cedula_representante.setText(" ");
        txt_color.setText(" ");
        txt_modificacion.setText(" ");
        txt_representante.setText(" ");
    }//GEN-LAST:event_bot_limpiarActionPerformed

    private void bot_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_agregarActionPerformed
        // TODO add your handling code here:
          if(txt_cedula_competidor.getText().equals("") || txt_cedula_representante.getText().equals("")
                || txt_color.getText().equals("") || txt_modificacion.getText().equals("") || txt_representante.getText().equals("")){
           
              lbl_error.setText("ingrese toda la informacion");
              }else {
    
                if (!txt_cedula_competidor.getText().trim().equals("")
                && JOptionPane.showConfirmDialog(this, "Seguro que desea guardar datos?", "Ingreso apariencia", 
                        JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE) == 0) {
            
                    apariencia ap = new apariencia(
                    
                    Integer.parseInt(txt_cedula_competidor.getText()),
                    Integer.parseInt(txt_cedula_representante.getText()),
                    txt_color.getText(),
                    txt_modificacion.getText(),
                    txt_representante.getText()
                    
            );
            autocontrolador.agregar(ap);
            
         }
             }
    }//GEN-LAST:event_bot_agregarActionPerformed

    private void txt_cedula_competidorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cedula_competidorKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
            
        if( txt_cedula_competidor.getText().length() >=10){
              evt.consume();
              JOptionPane.showMessageDialog(null, "maximo de ingreso 10 ");  
          }
          if(Character.isLetter(c)) {
              getToolkit().beep();
              
              evt.consume();
              
              JOptionPane.showMessageDialog(null, "ingrese solo numeros");
              
          }
    }//GEN-LAST:event_txt_cedula_competidorKeyTyped

    private void txt_colorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_colorKeyTyped
        // TODO add your handling code here:
          char c=evt.getKeyChar();
          if(Character.isDigit(c) ) {
              getToolkit().beep();
              evt.consume();
              JOptionPane.showMessageDialog(null, "ingrese solo letras ");  
          }
          
          if( txt_color.getText().length() >=20){
              evt.consume();
              JOptionPane.showMessageDialog(null, "maximo de ingreso de letras 20 ");  
          }
    }//GEN-LAST:event_txt_colorKeyTyped

    private void txt_cedula_representanteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cedula_representanteKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
            
        if( txt_cedula_representante.getText().length() >=10){
              evt.consume();
              JOptionPane.showMessageDialog(null, "maximo de ingreso 10 ");  
          }
          if(Character.isLetter(c)) {
              getToolkit().beep();
              
              evt.consume();
              
              JOptionPane.showMessageDialog(null, "ingrese solo numeros");
              
          }
    }//GEN-LAST:event_txt_cedula_representanteKeyTyped

    private void txt_modificacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_modificacionKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
          if(Character.isDigit(c) ) {
              getToolkit().beep();
              evt.consume();
              JOptionPane.showMessageDialog(null, "ingrese solo letras ");  
          }
          
          if( txt_modificacion.getText().length() >=30){
              evt.consume();
              JOptionPane.showMessageDialog(null, "maximo de ingreso de letras 30 ");  
          }
    }//GEN-LAST:event_txt_modificacionKeyTyped

    private void txt_representanteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_representanteKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
          if(Character.isDigit(c) ) {
              getToolkit().beep();
              evt.consume();
              JOptionPane.showMessageDialog(null, "ingrese solo letras ");  
          }
          
          if( txt_representante.getText().length() >=30){
              evt.consume();
              JOptionPane.showMessageDialog(null, "maximo de ingreso de letras 30 ");  
          }
    }//GEN-LAST:event_txt_representanteKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(apariencia1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(apariencia1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(apariencia1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(apariencia1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new apariencia1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bot_agregar;
    private javax.swing.JButton bot_limpiar;
    private javax.swing.JButton bot_siguiente;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lbl_error;
    private javax.swing.JTextField txt_cedula_competidor;
    private javax.swing.JTextField txt_cedula_representante;
    private javax.swing.JTextField txt_color;
    private javax.swing.JTextField txt_modificacion;
    private javax.swing.JTextField txt_representante;
    // End of variables declaration//GEN-END:variables
}
