/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.controladorapariencia;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.apariencia;

/**
 *
 * @author crist
 */
public class apariencia2 extends javax.swing.JFrame {

    DefaultTableModel modelo=new DefaultTableModel();
    controladorapariencia autocontrolador = new controladorapariencia();
    apariencia auto = new apariencia();
    
    /**
     * Creates new form apariencia2
     */
    public apariencia2() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_apariencia = new javax.swing.JTable();
        bot_mostrar = new javax.swing.JButton();
        bot_modificar = new javax.swing.JButton();
        bot_eliminar = new javax.swing.JButton();
        bot_limpiar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_cedulaCo = new javax.swing.JTextField();
        txt_cedulaRE = new javax.swing.JTextField();
        txt_color = new javax.swing.JTextField();
        txt_modificacion = new javax.swing.JTextField();
        txt_nombreRe = new javax.swing.JTextField();
        bot_actualizar = new javax.swing.JButton();
        bot_volver = new javax.swing.JButton();
        lbl_error = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setVisible(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Datos Apariencia");

        tbl_apariencia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Cedula Competidores", "Cedula Representante", "Color automovil", "modificaciones", "Nombre representante"
            }
        ));
        jScrollPane1.setViewportView(tbl_apariencia);

        bot_mostrar.setText("Mostrar");
        bot_mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_mostrarActionPerformed(evt);
            }
        });

        bot_modificar.setText("Modificar");
        bot_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_modificarActionPerformed(evt);
            }
        });

        bot_eliminar.setText("Eliminar");
        bot_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_eliminarActionPerformed(evt);
            }
        });

        bot_limpiar.setText("Limpiar");
        bot_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_limpiarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("MODIFICAR DATOS");

        jLabel3.setText("ID Cedula Competidor:");

        jLabel4.setText("Cedula representante:");

        jLabel5.setText("Color automovil:");

        jLabel6.setText("Modificaciones:");

        jLabel7.setText("Nombre representante:");

        txt_cedulaCo.setEditable(false);
        txt_cedulaCo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cedulaCoActionPerformed(evt);
            }
        });
        txt_cedulaCo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cedulaCoKeyTyped(evt);
            }
        });

        txt_cedulaRE.setEditable(false);

        txt_color.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_colorKeyTyped(evt);
            }
        });

        txt_modificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_modificacionKeyTyped(evt);
            }
        });

        txt_nombreRe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nombreReKeyTyped(evt);
            }
        });

        bot_actualizar.setText("Actualizar");
        bot_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_actualizarActionPerformed(evt);
            }
        });

        bot_volver.setText("Volver");
        bot_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_volverActionPerformed(evt);
            }
        });

        lbl_error.setText(".");

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bot_modificar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bot_mostrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bot_eliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bot_limpiar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_cedulaRE)
                    .addComponent(txt_cedulaCo)
                    .addComponent(txt_color, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(36, 36, 36)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_modificacion)
                        .addComponent(txt_nombreRe, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
                    .addComponent(bot_actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(262, 262, 262))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(192, 192, 192)
                        .addComponent(bot_volver, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(lbl_error, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(bot_volver))
                .addGap(36, 36, 36)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(bot_mostrar)
                        .addGap(18, 18, 18)
                        .addComponent(bot_modificar)
                        .addGap(28, 28, 28)
                        .addComponent(bot_eliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bot_limpiar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(23, 23, 23)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(txt_cedulaCo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_modificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(txt_cedulaRE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nombreRe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bot_actualizar))
                .addGap(18, 18, 18)
                .addComponent(lbl_error)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bot_mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_mostrarActionPerformed
        // TODO add your handling code here:
        mostrar();
    }//GEN-LAST:event_bot_mostrarActionPerformed

    private void bot_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_volverActionPerformed
        // TODO add your handling code here:
        apariencia1 re = new apariencia1();
        re.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bot_volverActionPerformed

    private void bot_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_modificarActionPerformed
        // TODO add your handling code here:
        int fila = tbl_apariencia.getSelectedRow();
        if(fila>=0){
            txt_cedulaCo.setText(tbl_apariencia.getValueAt(fila,0).toString());
            txt_cedulaRE.setText(tbl_apariencia.getValueAt(fila,1).toString());
            txt_color.setText(tbl_apariencia.getValueAt(fila,2).toString());
            txt_modificacion.setText(tbl_apariencia.getValueAt(fila,3).toString());
            txt_nombreRe.setText(tbl_apariencia.getValueAt(fila,4).toString());

        }else{
            JOptionPane.showMessageDialog(null, "No selecciono ninguna fila");
        }
    }//GEN-LAST:event_bot_modificarActionPerformed

    private void bot_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_eliminarActionPerformed
        // TODO add your handling code here:
         int fila = tbl_apariencia.getSelectedRow();

         int  confirmar = JOptionPane.showConfirmDialog(null, "desea eliminar el dato");
             if(confirmar==JOptionPane.OK_OPTION){
         String cod="";
         cod= tbl_apariencia.getValueAt(fila, 0).toString();
         
         autocontrolador.Eliminar(cod);
         
         if(fila > 0){
             
             JOptionPane.showMessageDialog(null, "Dato eliminado");
             modelo.removeRow(fila);
            
         }else{
             JOptionPane.showMessageDialog(null, "no selecciono ninguna fila");
         }
               
               int filaSeleccionada = tbl_apariencia.getSelectedRow();
             }
    }//GEN-LAST:event_bot_eliminarActionPerformed

    private void bot_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_limpiarActionPerformed
        // TODO add your handling code here:
        int fila = modelo.getRowCount();
           for(int i = 0;i < fila;i++){
           modelo.removeRow(0);
          }
           
          txt_cedulaCo.setText("");
          txt_cedulaRE.setText("");
          txt_color.setText("");
          txt_modificacion.setText("");
          txt_nombreRe.setText("");
    }//GEN-LAST:event_bot_limpiarActionPerformed

    private void bot_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_actualizarActionPerformed
        // TODO add your handling code here:
        if(txt_cedulaCo.getText().equals("") || txt_cedulaRE.getText().equals("")
                || txt_color.getText().equals("") || txt_modificacion.getText().equals("") || txt_nombreRe.getText().equals("")){
           
              lbl_error.setText("ingrese toda la informacion");
              }else {
    
                if (!txt_cedulaCo.getText().trim().equals("")
                && JOptionPane.showConfirmDialog(this, "Seguro que desea actualizar datos?", "modificar apariencia", 
                        JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE) == 0) {
            
                    
                   apariencia ap = new apariencia(
                    
                    Integer.parseInt(txt_cedulaCo.getText()),
                    Integer.parseInt(txt_cedulaRE.getText()),
                    txt_color.getText(),
                    txt_modificacion.getText(),
                    txt_nombreRe.getText()
                    
            );
            autocontrolador.ModificarDatos(ap);
            
         }
             }
    }//GEN-LAST:event_bot_actualizarActionPerformed

    private void txt_cedulaCoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cedulaCoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cedulaCoActionPerformed

    private void txt_cedulaCoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cedulaCoKeyTyped
        //
    }//GEN-LAST:event_txt_cedulaCoKeyTyped

    private void txt_colorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_colorKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
            
        if( txt_color.getText().length() >=20){
              evt.consume();
              JOptionPane.showMessageDialog(null, "maximo de ingreso 20 ");  
          }
          if(Character.isDigit(c) ) {
              getToolkit().beep();
              evt.consume();
              JOptionPane.showMessageDialog(null, "ingrese solo letras ");  
          }
    }//GEN-LAST:event_txt_colorKeyTyped

    private void txt_modificacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_modificacionKeyTyped
        char c=evt.getKeyChar();
            
        if( txt_modificacion.getText().length() >=30){
              evt.consume();
              JOptionPane.showMessageDialog(null, "maximo de ingreso 30 ");  
          }
          if(Character.isDigit(c) ) {
              getToolkit().beep();
              evt.consume();
              JOptionPane.showMessageDialog(null, "ingrese solo letras ");  
          }
    }//GEN-LAST:event_txt_modificacionKeyTyped

    private void txt_nombreReKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombreReKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
            
        if( txt_nombreRe.getText().length() >=30){
              evt.consume();
              JOptionPane.showMessageDialog(null, "maximo de ingreso 30 ");  
          }
          if(Character.isDigit(c) ) {
              getToolkit().beep();
              evt.consume();
              JOptionPane.showMessageDialog(null, "ingrese solo letras ");  
          }
    }//GEN-LAST:event_txt_nombreReKeyTyped

    
     private void mostrar() {          
        modelo = (DefaultTableModel)tbl_apariencia.getModel();
        List<apariencia> lista = autocontrolador.listarapariencia();
        Object[] objeto = new Object[5];
        for (int i = 0; i < lista.size(); i++) {
            objeto[0] = lista.get(i).getCedulaCo();
            objeto[1] = lista.get(i).getCedulaRe();
            objeto[2] = lista.get(i).getColor();
            objeto[3] = lista.get(i).getModificacion();
            objeto[4] = lista.get(i).getNombreRe();
            modelo.addRow(objeto);
        }
                  
    }
     
     public void limpiarTabla() {
        for (int i = 0; i < tbl_apariencia.getRowCount(); i++) {
            modelo.removeRow(i);
            i = i - 1;
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(apariencia2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(apariencia2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(apariencia2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(apariencia2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new apariencia2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bot_actualizar;
    private javax.swing.JButton bot_eliminar;
    private javax.swing.JButton bot_limpiar;
    private javax.swing.JButton bot_modificar;
    private javax.swing.JButton bot_mostrar;
    private javax.swing.JButton bot_volver;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_error;
    private javax.swing.JTable tbl_apariencia;
    private javax.swing.JTextField txt_cedulaCo;
    private javax.swing.JTextField txt_cedulaRE;
    private javax.swing.JTextField txt_color;
    private javax.swing.JTextField txt_modificacion;
    private javax.swing.JTextField txt_nombreRe;
    // End of variables declaration//GEN-END:variables
}
