/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.controladorAutos;
import javax.swing.JOptionPane;
import modelo.autos;

/**
 *
 * @author crist
 */
public class autos2 extends javax.swing.JFrame {
    
    controladorAutos autocontrolador = new controladorAutos();

    /**
     * Creates new form autos2
     */
    public autos2() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_matricula = new javax.swing.JTextField();
        txt_cedula = new javax.swing.JTextField();
        txt_modelo = new javax.swing.JTextField();
        txt_nombre_dueño = new javax.swing.JTextField();
        bot_ingresar = new javax.swing.JButton();
        bot_siguiente = new javax.swing.JButton();
        lbl_error = new javax.swing.JLabel();
        bot_limpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Ingreso Datos Autos");

        jLabel2.setText("Matricula:");

        jLabel3.setText("Cedula:");

        jLabel4.setText("Modelo:");

        jLabel5.setText("Nombre del dueño:");

        txt_matricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_matriculaActionPerformed(evt);
            }
        });
        txt_matricula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_matriculaKeyTyped(evt);
            }
        });

        txt_cedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cedulaKeyTyped(evt);
            }
        });

        txt_modelo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_modeloKeyTyped(evt);
            }
        });

        txt_nombre_dueño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombre_dueñoActionPerformed(evt);
            }
        });
        txt_nombre_dueño.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nombre_dueñoKeyTyped(evt);
            }
        });

        bot_ingresar.setText("Ingresar");
        bot_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_ingresarActionPerformed(evt);
            }
        });

        bot_siguiente.setText("Siguiente>");
        bot_siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_siguienteActionPerformed(evt);
            }
        });

        lbl_error.setText(".");

        bot_limpiar.setText("Limpiar");
        bot_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_limpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(95, 95, 95))
                    .addComponent(bot_siguiente, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_cedula, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                .addComponent(txt_modelo, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txt_nombre_dueño, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txt_matricula))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(bot_limpiar))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_error, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(90, 90, 90))
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(bot_ingresar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_matricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_nombre_dueño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbl_error)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bot_ingresar)
                    .addComponent(bot_limpiar))
                .addGap(21, 21, 21)
                .addComponent(bot_siguiente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nombre_dueñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombre_dueñoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombre_dueñoActionPerformed

    private void bot_siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_siguienteActionPerformed
        autos1 ingreso = new autos1();
        ingreso.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bot_siguienteActionPerformed

    private void bot_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_ingresarActionPerformed
        if(txt_cedula.getText().equals("") || txt_matricula.getText().equals("")
                || txt_modelo.getText().equals("") || txt_nombre_dueño.getText().equals("")){
           
              lbl_error.setText("ingrese toda la informacion");
              }else {
    
                if (!txt_cedula.getText().trim().equals("")
                && JOptionPane.showConfirmDialog(this, "Seguro que desea guardar datos?", "Ingreso auto", 
                        JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE) == 0) {
            
                    autos au = new autos(
                    
                    txt_matricula.getText(),
                    txt_modelo.getText(),
                    txt_nombre_dueño.getText(),
                    Integer.parseInt(txt_cedula.getText())
                    
            );
            autocontrolador.agregar(au);
            
         }
             }
    }//GEN-LAST:event_bot_ingresarActionPerformed

    private void bot_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_limpiarActionPerformed
        txt_cedula.setText(" ");
        txt_matricula.setText(" ");
        txt_modelo.setText(" ");
        txt_nombre_dueño.setText(" ");
    }//GEN-LAST:event_bot_limpiarActionPerformed

    private void txt_matriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_matriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_matriculaActionPerformed

    private void txt_matriculaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_matriculaKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
            
        if( txt_matricula.getText().length() >=7){
              evt.consume();
              JOptionPane.showMessageDialog(null, "maximo de ingreso 7 ");  
          }
          
    }//GEN-LAST:event_txt_matriculaKeyTyped

    private void txt_cedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cedulaKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
            
        if( txt_cedula.getText().length() >=10){
              evt.consume();
              JOptionPane.showMessageDialog(null, "maximo de ingreso 10 ");  
          }
          if(Character.isLetter(c)) {
              getToolkit().beep();
              
              evt.consume();
              
              JOptionPane.showMessageDialog(null, "ingrese solo numeros");
              
          }
    }//GEN-LAST:event_txt_cedulaKeyTyped

    private void txt_modeloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_modeloKeyTyped
        // TODO add your handling code here:
        
        char c=evt.getKeyChar();
            
        if( txt_modelo.getText().length() >=20){
              evt.consume();
              JOptionPane.showMessageDialog(null, "maximo de ingreso 20 ");  
          }
          if(Character.isDigit(c) ) {
              getToolkit().beep();
              evt.consume();
              JOptionPane.showMessageDialog(null, "ingrese solo letras ");  
          }
    }//GEN-LAST:event_txt_modeloKeyTyped

    private void txt_nombre_dueñoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombre_dueñoKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
            
        if( txt_nombre_dueño.getText().length() >=30){
              evt.consume();
              JOptionPane.showMessageDialog(null, "maximo de ingreso 30 ");  
          }
          if(Character.isDigit(c) ) {
              getToolkit().beep();
              evt.consume();
              JOptionPane.showMessageDialog(null, "ingrese solo letras ");  
          }
    }//GEN-LAST:event_txt_nombre_dueñoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(autos2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(autos2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(autos2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(autos2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new autos2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bot_ingresar;
    private javax.swing.JButton bot_limpiar;
    private javax.swing.JButton bot_siguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lbl_error;
    private javax.swing.JTextField txt_cedula;
    private javax.swing.JTextField txt_matricula;
    private javax.swing.JTextField txt_modelo;
    private javax.swing.JTextField txt_nombre_dueño;
    // End of variables declaration//GEN-END:variables
}
