/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.controladorAutos;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.autos;



/**
 *
 * @author crist
 */
public class autos1 extends javax.swing.JFrame {

    DefaultTableModel modelo=new DefaultTableModel();
    controladorAutos autocontrolador = new controladorAutos();
    autos auto = new autos();

    
    /**
     * Creates new form autos
     */
    public autos1() {
        initComponents();
        this.setLocationRelativeTo(null);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_tabla = new javax.swing.JTable();
        bot_mostrar = new javax.swing.JButton();
        bot_modificar = new javax.swing.JButton();
        bot_eliminar = new javax.swing.JButton();
        bot_limpiar = new javax.swing.JButton();
        lbl_titulo2 = new javax.swing.JLabel();
        bot_volver = new javax.swing.JButton();
        lbl_matricula = new javax.swing.JLabel();
        lbl_cedula = new javax.swing.JLabel();
        lbl_modelo = new javax.swing.JLabel();
        lbl_nombreD = new javax.swing.JLabel();
        txt_matricula = new javax.swing.JTextField();
        txt_cedula = new javax.swing.JTextField();
        txt_modelo = new javax.swing.JTextField();
        txt_nombreD = new javax.swing.JTextField();
        bot_actualizar = new javax.swing.JButton();
        lbl_error = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setVisible(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Datos Autos");

        tbl_tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matricula", "Cedula", "Modelo", "nombre del dueño"
            }
        ));
        jScrollPane1.setViewportView(tbl_tabla);

        bot_mostrar.setText("Mostrar");
        bot_mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_mostrarActionPerformed(evt);
            }
        });

        bot_modificar.setText("Modificar");
        bot_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_modificarActionPerformed(evt);
            }
        });

        bot_eliminar.setText("Eliminar");
        bot_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_eliminarActionPerformed(evt);
            }
        });

        bot_limpiar.setText("Limpiar");
        bot_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_limpiarActionPerformed(evt);
            }
        });

        lbl_titulo2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_titulo2.setText("Modificar Datos");

        bot_volver.setText("volver");
        bot_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_volverActionPerformed(evt);
            }
        });

        lbl_matricula.setText("Matricula:");

        lbl_cedula.setText("Cedula:");

        lbl_modelo.setText("Modelo:");

        lbl_nombreD.setText("Nombre del dueño:");

        txt_matricula.setEditable(false);

        txt_cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cedulaActionPerformed(evt);
            }
        });
        txt_cedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cedulaKeyTyped(evt);
            }
        });

        txt_modelo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_modeloKeyTyped(evt);
            }
        });

        txt_nombreD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nombreDKeyTyped(evt);
            }
        });

        bot_actualizar.setText("Actualizar");
        bot_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_actualizarActionPerformed(evt);
            }
        });

        lbl_error.setText(".");

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(196, 196, 196)
                        .addComponent(bot_volver))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(lbl_nombreD)
                                .addGap(58, 58, 58)
                                .addComponent(txt_nombreD, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jInternalFrame1Layout.createSequentialGroup()
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_cedula)
                                    .addComponent(lbl_modelo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_modelo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_cedula, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jInternalFrame1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(lbl_matricula)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_matricula, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bot_actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bot_modificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bot_mostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bot_eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bot_limpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGap(241, 241, 241)
                                .addComponent(lbl_titulo2)))
                        .addGap(0, 31, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(lbl_error, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(bot_volver))
                .addGap(43, 43, 43)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(bot_mostrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bot_modificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bot_eliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bot_limpiar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(lbl_titulo2)
                .addGap(46, 46, 46)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_matricula, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_matricula, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bot_actualizar))
                        .addGap(38, 38, 38)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(txt_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_nombreD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_nombreD)))
                            .addComponent(lbl_modelo)))
                    .addComponent(lbl_cedula))
                .addGap(18, 18, 18)
                .addComponent(lbl_error)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bot_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_volverActionPerformed
        autos2 volver = new autos2();
        volver.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bot_volverActionPerformed

    private void bot_mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_mostrarActionPerformed
        mostrar();
    }//GEN-LAST:event_bot_mostrarActionPerformed

    private void bot_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_modificarActionPerformed
        // TODO add your handling code here:
        int fila = tbl_tabla.getSelectedRow();
        if(fila>=0){
            txt_matricula.setText(tbl_tabla.getValueAt(fila,0).toString());
            txt_cedula.setText(tbl_tabla.getValueAt(fila,1).toString());
            txt_modelo.setText(tbl_tabla.getValueAt(fila,2).toString());
            txt_nombreD.setText(tbl_tabla.getValueAt(fila,3).toString());

        }else{
            JOptionPane.showMessageDialog(null, "No selecciono ninguna fila");
        }
    }//GEN-LAST:event_bot_modificarActionPerformed

    private void bot_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_actualizarActionPerformed
        // TODO add your handling code here:
        if(txt_cedula.getText().equals("") || txt_matricula.getText().equals("")
                || txt_modelo.getText().equals("") || txt_nombreD.getText().equals("")){
           
              lbl_error.setText("ingrese toda la informacion");
              }else {
    
                if (!txt_cedula.getText().trim().equals("")
                && JOptionPane.showConfirmDialog(this, "Seguro que desea guardar datos?", "modificar auto", 
                        JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE) == 0) {
            
                    
                    autos au = new autos(
                    
                    txt_matricula.getText(),
                    txt_modelo.getText(),
                    txt_nombreD.getText(),
                    Integer.parseInt(txt_cedula.getText())
                    
            );
            autocontrolador.ModificarDatos(au);
            
         }
             }
    }//GEN-LAST:event_bot_actualizarActionPerformed

    private void bot_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_limpiarActionPerformed
        // TODO add your handling code here:
          int fila = modelo.getRowCount();
           for(int i = 0;i < fila;i++){
           modelo.removeRow(0);
          }
           
          txt_cedula.setText("");
          txt_matricula.setText("");
          txt_modelo.setText("");
          txt_nombreD.setText("");
          
    }//GEN-LAST:event_bot_limpiarActionPerformed

    private void bot_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_eliminarActionPerformed
        // TODO add your handling code here:
        int fila = tbl_tabla.getSelectedRow();

        int  confirmar = JOptionPane.showConfirmDialog(null, "desea eliminar el dato");
             if(confirmar==JOptionPane.OK_OPTION){
         String cod="";
         cod= tbl_tabla.getValueAt(fila, 0).toString();
         
         autocontrolador.Eliminar(cod);
         
         if(fila > 0){
             
             JOptionPane.showMessageDialog(null, "Dato eliminado");
             modelo.removeRow(fila);
            
         }else{
             JOptionPane.showMessageDialog(null, "no selecciono ninguna fila");
         }
               
               int filaSeleccionada = tbl_tabla.getSelectedRow();
             }       

    }//GEN-LAST:event_bot_eliminarActionPerformed

    private void txt_cedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cedulaActionPerformed

    private void txt_cedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cedulaKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
            
        if( txt_cedula.getText().length() >=10){
              evt.consume();
              JOptionPane.showMessageDialog(null, "maximo de ingreso 10 ");  
          }
          if(Character.isLetter(c)) {
              getToolkit().beep();
              
              evt.consume();
              
              JOptionPane.showMessageDialog(null, "ingrese solo numeros");
              
          }
    }//GEN-LAST:event_txt_cedulaKeyTyped

    private void txt_modeloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_modeloKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
            
        if( txt_modelo.getText().length() >=20){
              evt.consume();
              JOptionPane.showMessageDialog(null, "maximo de ingreso 20 ");  
          }
          if(Character.isDigit(c) ) {
              getToolkit().beep();
              evt.consume();
              JOptionPane.showMessageDialog(null, "ingrese solo letras ");  
          }
    }//GEN-LAST:event_txt_modeloKeyTyped

    private void txt_nombreDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombreDKeyTyped
        // TODO add your handling code here:
         char c=evt.getKeyChar();
            
        if( txt_nombreD.getText().length() >=30){
              evt.consume();
              JOptionPane.showMessageDialog(null, "maximo de ingreso 30 ");  
          }
          if(Character.isDigit(c) ) {
              getToolkit().beep();
              evt.consume();
              JOptionPane.showMessageDialog(null, "ingrese solo letras ");  
          }
    }//GEN-LAST:event_txt_nombreDKeyTyped

    
    private void mostrar() {          
        modelo = (DefaultTableModel)tbl_tabla.getModel();
        List<autos> lista = autocontrolador.listarautos();
        Object[] objeto = new Object[4];
        for (int i = 0; i < lista.size(); i++) {
            objeto[0] = lista.get(i).getMatricula();
            objeto[1] = lista.get(i).getCedula();
            objeto[2] = lista.get(i).getModelo();
            objeto[3] = lista.get(i).getNombreDueño();
            modelo.addRow(objeto);
        }
                  
    }
    
     public void limpiarTabla() {
        for (int i = 0; i < tbl_tabla.getRowCount(); i++) {
            modelo.removeRow(i);
            i = i - 1;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(autos1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(autos1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(autos1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(autos1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new autos1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton bot_actualizar;
    public javax.swing.JButton bot_eliminar;
    public javax.swing.JButton bot_limpiar;
    public javax.swing.JButton bot_modificar;
    public javax.swing.JButton bot_mostrar;
    public javax.swing.JButton bot_volver;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_cedula;
    private javax.swing.JLabel lbl_error;
    private javax.swing.JLabel lbl_matricula;
    private javax.swing.JLabel lbl_modelo;
    private javax.swing.JLabel lbl_nombreD;
    private javax.swing.JLabel lbl_titulo2;
    public javax.swing.JTable tbl_tabla;
    public javax.swing.JTextField txt_cedula;
    public javax.swing.JTextField txt_matricula;
    public javax.swing.JTextField txt_modelo;
    private javax.swing.JTextField txt_nombreD;
    // End of variables declaration//GEN-END:variables
}
